// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgrI_7AIYkmGQa6fy_3CafiZq7r4P7z_4',
    appId: '1:1095165497045:web:7ee3ce99ef672db6c59c5c',
    messagingSenderId: '1095165497045',
    projectId: 'streampro-9774e',
    authDomain: 'streampro-9774e.firebaseapp.com',
    storageBucket: 'streampro-9774e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnDGCqamaIYCxlaesxCseXV9xsPIRtEnA',
    appId: '1:1095165497045:android:778eada03498b34ec59c5c',
    messagingSenderId: '1095165497045',
    projectId: 'streampro-9774e',
    storageBucket: 'streampro-9774e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFs8xLtfKhhHSHnU5CFaUsoVHxcAzl4Ag',
    appId: '1:1095165497045:ios:6102c517fd9ad48ac59c5c',
    messagingSenderId: '1095165497045',
    projectId: 'streampro-9774e',
    storageBucket: 'streampro-9774e.appspot.com',
    iosClientId: '1095165497045-ih1npkuf69o0e88dnl68jl7u0738s9n9.apps.googleusercontent.com',
    iosBundleId: 'com.example.streamPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFs8xLtfKhhHSHnU5CFaUsoVHxcAzl4Ag',
    appId: '1:1095165497045:ios:6102c517fd9ad48ac59c5c',
    messagingSenderId: '1095165497045',
    projectId: 'streampro-9774e',
    storageBucket: 'streampro-9774e.appspot.com',
    iosClientId: '1095165497045-ih1npkuf69o0e88dnl68jl7u0738s9n9.apps.googleusercontent.com',
    iosBundleId: 'com.example.streamPro',
  );
}
